from backend.db.repository.fetch_raw_data import fetch_last_days_posts
from workflow.workflow import graph

async def run_entire_flow():
    for post in fetch_last_days_posts():
        initial_state = {
            "user_input": None,              #    given to the orchestrator or supervisor by human.
            "messages": [],                  #    for AI conversations.
            "data": post["description"],    #     data:Optional[str]                
            "topic": post["title"],         #     yet to be finalize.
            "title": post["title"],         #     title:Optional[str]
            "summary": None,                #     generated by ai
            "description":None,             #     generated by AI
            "arxiv_urls": [],                #    found from arxiv 
            "documents": [],                 #    docs from arxiv
            "tavily_search_result": None,    #    search result by agent. 
            "code": None,                     #   generated by agent.
            # "name":post['source_name'],     #   yet to be discussed
        }

        final_state = graph.ainvoke(initial_state)

        return final_state
    


    
